apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  labels:
    run: nodeservice
spec:
  type: NodePort
  ports:
    - port: 3001
      nodePort: 30001
      targetPort: 3001
      protocol: TCP
  selector:
    run: nodeservice
