on:
  push:
    branches:
      - nasa-ingestor
  release:
    types:
      - created

jobs:
  ossie_job:
    runs-on: ubuntu-latest
    name: Audit Python dependencies 
    steps:
      - uses: actions/checkout@v2
      - name: Set directory
        working-directory: ./ingestor
      - uses: sbmthakur/Ossie-GHA@main
        with:
          OSSIEBOT_ID: ${{ secrets.OSSIEBOT_ID }}
