on:
  push:
    branches:
      - nasa-ingestor
  release:
    types:
      - created

jobs:
  ossie_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ingestor
    name: Audit Python dependencies 
    steps:
      - uses: sbmthakur/Ossie-GHA@main
        with:
          OSSIEBOT_ID: ${{ secrets.OSSIEBOT_ID }}
